#include "ast/ast_pp.h"
#include "ast/for_each_expr.h"
#include "smt/theory_str_noodler/lia_solver.h"

namespace smt::noodler {

    lia_solver::lia_solver(ast_manager& m):
        m(m), m_util_s(m), initialized(false), erv(m), model_formula(m), unsat_core(m) {
    }

    void lia_solver::reset_result() {
        model_formula = expr_ref(m.mk_true(), m);
        unsat_core = expr_ref(m.mk_true(), m);
    }

    void lia_solver::compute_unsat_core(const expr_ref_vector& raw_core) {
        for (expr* c : raw_core) {
            unsat_core = m.mk_and(unsat_core, c);
        }
        STRACE(str_lia, tout << "UNSAT core:" << std::endl << mk_pp(unsat_core, m));
    }

    expr_ref lia_solver::eval_arith_str_func(app* a, model_ref& mdl) {
        SASSERT(util::is_arith_str_func(a, m_util_s) && a->get_num_args() == 1);
        func_interp* fi = mdl->get_func_interp(a->get_decl());
        expr_ref arg_val(m);
        if (fi != nullptr && mdl->eval_expr(a->get_arg(0), arg_val) && m.is_value(arg_val)) {
            expr* args[1] = { arg_val.get() };
            func_entry* entry = fi->get_entry(args);
            if (entry != nullptr) {
                return expr_ref(entry->get_result(), m);
            }
            // no entry for the argument's value => it is not equal to any value in the table (see the
            // documentation in the header), so its value is the else value
            expr* else_val = fi->get_else();
            if (else_val != nullptr && is_ground(else_val)) {
                return expr_ref(else_val, m);
            }
        }
        expr_ref res(m);
        mdl->eval_expr(a, res);
        return res;
    }

    void lia_solver::compute_model_formula(expr* e, model_ref& mdl) {
        // Collect int/real variables and str.len/str.to_code/str.to_int/str.to_real applications. We skip
        // applications that are not ground, i.e., those depending on a quantified variable, as they do not
        // have a single value.
        struct collect_terms {
            ast_manager &m;
            seq_util m_util_s;
            expr_ref_vector vars;
            expr_ref_vector arith_str_apps;

            collect_terms(ast_manager &m) : m(m), m_util_s(m), vars(m), arith_str_apps(m) {}
            void operator()(expr* e) {
                if (util::is_arith_str_func(e, m_util_s)) {
                    if (is_ground(e)) {
                        arith_str_apps.push_back(e);
                    }
                } else if (!m_util_s.is_string(e->get_sort()) && util::is_variable(e)) {
                    vars.push_back(e);
                }
            }
        };
        collect_terms ct(m);
        for_each_expr(ct, e);
        for (expr* v : ct.vars) {
            expr_ref res(m);
            mdl->eval_expr(v, res);
            STRACE(str_lia, tout << "Model for " << mk_pp(v, m) << " is " << mk_pp(res, m) << std::endl;);
            model_formula = m.mk_and(model_formula, m.mk_eq(v, res));
        }
        for (expr* a : ct.arith_str_apps) {
            expr_ref res = eval_arith_str_func(to_app(a), mdl);
            STRACE(str_lia, tout << "Model for " << mk_pp(a, m) << " is " << mk_pp(res, m) << std::endl;);
            model_formula = m.mk_and(model_formula, m.mk_eq(a, res));
        }
    }

    void lia_solver::initialize(context& ctx, bool include_assignment, bool include_clauses) {
        if (!initialized) {
            initialized = true;
            expr_ref_vector Assigns(m);
            ctx.get_assignments(Assigns);
            for (unsigned i = 0; i < ctx.get_num_asserted_formulas(); ++i) {
                STRACE(str_lia, tout << "check_sat context from asserted: " << mk_pp(ctx.get_asserted_formula(i), m) << std::endl);
                assert_expr(ctx.get_asserted_formula(i));
            }
            if (include_assignment) {
                for (auto& e : Assigns) {
                    if (ctx.is_relevant(e)) {
                        STRACE(str_lia, tout << "check_sat context from assign: " << mk_pp(e, m) << std::endl);
                        assert_expr(e);
                    }
                }
            }
            if (include_clauses) {
                // Assigns/get_asserted_formula only expose the original assertions and literals that
                // already have a concrete truth value. Clauses with still-undecided literals (e.g. a
                // semantic axiom for str.substr/str.indexof relating a proxy variable to a real problem
                // variable, guarded by not-yet-decided bound checks) are otherwise invisible here, so
                // include them too -- important when you want to use the model generated by this LIA solver.
                expr_ref_vector context_clauses(m);
                auto collect = [this, &ctx, &context_clauses](const clause_vector& clauses) {
                    for (clause* c : clauses) {
                        unsigned num_lits = c->get_num_literals();
                        if (num_lits == 0) {
                            continue;
                        }
                        expr_ref_vector lits(m);
                        for (unsigned i = 0; i < num_lits; ++i) {
                            lits.push_back(ctx.literal2expr(c->get_literal(i)));
                        }
                        context_clauses.push_back(lits.size() == 1 ? lits.get(0) : m.mk_or(lits.size(), lits.data()));
                    }
                };
                collect(ctx.get_lemmas());
                collect(ctx.get_aux_clauses());
                for (expr* cl : context_clauses) {
                    STRACE(str_lia, tout << "check_sat context from clause: " << mk_pp(cl, m) << std::endl);
                    assert_expr(cl);
                }
            }
        }
    }

    void lia_solver::assert_expr(expr* e) {
        erv.push_back(e);
    }

    void lia_solver::get_unsat_core(expr_ref& dst) {
        dst = unsat_core;
    }

    expr_ref lia_solver::get_model() {
        return model_formula;
    }

}
